name: installer
on:
  push:
    branches:
      - main

jobs:
  installer:
    runs-on: windows-latest

    steps:
      - name: Download build artifact
        run: |
          curl -o Trae-Windows-Executable.zip https://beaches-assure-seemed-christine.trycloudflare.com/Trae-Windows-Executable.zip

      - name: Extract the outer zip
        run: |
          mkdir extracted
          7z x Trae-Windows-Executable.zip -oextracted

      - name: Extract the inner zip
        run: |
          mkdir Trae-win32-x64
          7z x extracted/Trae-win32-x64.zip -oTrae-win32-x64

      - name: Download Inno Setup
        run: |
          curl -o inno.zip https://beaches-assure-seemed-christine.trycloudflare.com/inno.zip
          mkdir inno
          7z x inno.zip -oinno

      - name: Download Inno Setup script
        run: |
          curl -o setup.iss https://beaches-assure-seemed-christine.trycloudflare.com/setup.iss

      - name: Verify extracted structure
        run: |
          dir Trae-win32-x64

      - name: Create installer
        run: |
          & "inno\Inno Setup 6\ISCC.exe" setup.iss

      - name: Upload installer artifact
        uses: actions/upload-artifact@v3
        with:
          name: Trae-win32-x64-Installer
          path: "**/Output/*.exe"
