name: installer
on:
  push:
    branches:
      - main

jobs:
  installer:
    runs-on: windows-latest

    steps:
      - name: Download build artifact
        run: |
          curl -o Trae-Windows-Executable.zip https://beaches-assure-seemed-christine.trycloudflare.com/Trae-Windows-Executable.zip

      - name: Extract the outer zip
        run: |
          mkdir extracted
          7z x Trae-Windows-Executable.zip -oextracted

      - name: Extract the inner zip
        run: |
          mkdir extracted_inner
          7z x extracted/Trae-win32-x64.zip -oextracted_inner

      - name: Download Inno Setup script
        run: |
          curl -o setup.iss https://beaches-assure-seemed-christine.trycloudflare.com/setup.iss

      - name: Install Inno Setup
        run: |
          choco install innosetup --yes

      - name: Create installer
        run: |
          cmd.exe /c "C:\Program Files (x86)\Inno Setup 6\ISCC.exe setup.iss"

      - name: Upload installer artifact
        uses: actions/upload-artifact@v3
        with:
          name: Trae-win32-x64-Installer
          path: "Output/*.exe"
