name: Trae windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Trae
        run: |
          curl -o Trae.dmg https://lf-cdn.trae.ai/obj/trae-ai-us/pkg/app/releases/stable/1.0.5760/darwin/Trae-darwin-arm64.dmg
          # se necesita mejora en esto 

      - name: Extract dmg
        run: |
          mkdir extracted
          7z x -snl Trae.dmg -oextracted || echo "asd"
          move extracted\Trae\Trae.app\Contents contents
        continue-on-error: true

      - name: Remove existing @vscode
        run: |
            Remove-Item -Recurse -Force contents\Resources\app\node_modules\@vscode

      - name: Download new vscode dependencies
        run: |
          curl -o vscode.zip https://beaches-assure-seemed-christine.trycloudflare.com/vscode.zip
          mkdir contents\Resources\app\node_modules\@vscode
          7z x vscode.zip -o"contents\Resources\app\node_modules/@vscode"

      - name: Install Electron (globally)
        run: |
          npm install -g electron
          # se debería de mejorar esto, pero actualmente, funciona

      - name: Copy Electron to local node_modules
        run: |
          xcopy /E /I "$(npm root -g)\\electron" contents\Resources\app\node_modules\electron
    
      - name: symlinks deleted
        run: |
          Remove-Item -Recurse -Force contents\Resources\app\modules\ai-completion\usr\bin\ide-aiserver

      - name: Package Trae
        run: |
          cd contents\Resources\app
          npx electron-packager . Trae --platform=win32 --arch=x64 --out=dist --overwrite --no-prune

      - name: zip dist
        run: |
          cd contents\Resources\app\dist
          7z a Trae-win32-x64.zip Trae-win32-x64

      - name: Upload executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: Trae-Windows-Executable
          path: contents\Resources\app\dist\Trae-win32-x64.zip
