name: Trae Windows
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Trae
        run: |
          curl -o Trae.dmg https://lf-cdn.trae.ai/obj/trae-ai-us/pkg/app/releases/stable/1.0.5760/darwin/Trae-darwin-arm64.dmg

      - name: Extract dmg
        run: |
          mkdir extracted
          7z x -snl Trae.dmg -oextracted
          move extracted\Trae\Trae.app\Contents contents
        continue-on-error: true

      - name: Download new dependencies
        run: |
          curl -o dependencias.zip https://github.com/polo-1245-oficial/traeAI/raw/refs/heads/main/files/dependencias.zip
          7z x dependencias.zip -o"contents\Resources\app\node_modules" -y

      - name: Install Electron (globally)
        run: |
          npm install -g electron

      - name: Copy Electron to local node_modules
        run: |
          xcopy /E /I "$(npm root -g)\\electron" contents\Resources\app\node_modules\electron

      - name: Remove problematic symlinks
        run: |
          Remove-Item -Recurse -Force contents\Resources\app\modules\ai-completion\usr\bin\ide-aiserver

      - name: Package Trae
        run: |
          cd contents\Resources\app
          npx electron-packager . Trae --platform=win32 --arch=x64 --out=dist --overwrite --no-prune

      - name: Prepare files for installer
        run: |
          mkdir Trae-win32-x64
          move contents\Resources\app\dist\Trae-win32-x64\* Trae-win32-x64

      - name: Download Inno Setup
        run: |
          curl -o inno.zip https://github.com/polo-1245-oficial/traeAI/raw/refs/heads/main/files/inno.zip
          mkdir inno
          7z x inno.zip -oinno

      - name: Download Inno Setup script
        run: |
          curl -o setup.iss https://github.com/polo-1245-oficial/traeAI/raw/refs/heads/main/files/setup.iss

      - name: Verify extracted structure
        run: |
          dir Trae-win32-x64

      - name: Create installer
        run: |
          & "inno\Inno Setup 6\ISCC.exe" setup.iss

      - name: Upload installer artifact
        uses: actions/upload-artifact@v3
        with:
          name: Trae-win32-x64-Installer
          path: "**/Output/*.exe"
